#ifndef _ECS_H_
#define _ECS_H_


namespace ECS
{
    #define ECS_COMPONENT_TYPE_DEFAULT 0
	#define ECS_COMPONENT_TYPE_TEST 1
    #define ECS_ENTITY_TYPE_DEFAULT 0

}

enum ECS_PLAYER_COMPONENT_TYPE
{
	ECS_PLAYER_COMPONENT_TYPE_NONE = ECS_COMPONENT_TYPE_DEFAULT,
    ECS_PLAYER_COMPONENT_TYPE_TEST = ECS_COMPONENT_TYPE_TEST,
    ECS_PLAYER_COMPONENT_TYPE_PLAYER,
	ECS_PLAYER_COMPONENT_TYPE_COUNTER,
    ECS_PLAYER_COMPONENT_TYPE_BAG,
    ECS_PLAYER_COMPONENT_TYPE_MAIL,
	ECS_PLAYER_COMPONENT_TYPE_QUEST,

    ECS_PLAYER_COMPONENT_TYPE_MAX

};

enum ECS_CHAR_COMPONENT_TYPE
{
	ECS_CHAR_COMPONENT_TYPE_NONE = ECS_COMPONENT_TYPE_DEFAULT,
	ECS_CHAR_COMPONENT_TYPE_TEST = ECS_COMPONENT_TYPE_TEST,
	ECS_CHAR_COMPONENT_TYPE_BEHAVIAC,
	ECS_CHAR_COMPONENT_TYPE_FIGHT,

	ECS_CHAR_COMPONENT_TYPE_MAX

};

enum ECS_ENTITY_TYPE
{
    ECS_ENTITY_TYPE_NONE = ECS_ENTITY_TYPE_DEFAULT,
    ECS_ENTITY_TYPE_TEST,
    ECS_ENTITY_TYPE_PLAYER,
	ECS_ENTITY_TYPE_CHAR,

    ECS_ENTITY_TYPE_MAX

};


#endif

